### ISSUE TITLE
Running predictor-dynamic.py

### ISSUE THREAD

**Issue by hsezhiyan** [SLP-team/SLP-Core#13]
When I try to run predictor-dynamic.py (after having installed the data folder), I got the following error:

tensorflow.python.framework.errors_impl.NotFoundError: simple-examples/data/train; No such file or directory

Do you know what the issue is? I correctly downloaded and unpacked the TAR file.

**Comment by VHellendoorn** [comment]
Hi there,

I am guessing that you followed the instructions in the comments at the top of that file. These belonged to the original version of that code and were related to modeling the PTB examples; I should have removed these, sorry. I am not entirely sure why it complains about that datapath, it is possible that the "simple-examples" did not use "data/train" (and similar) paths and I just hard-coded the paths for my task in the data_reader.py file.

But taking a step back, this file was specifically used to evaluate a trained model with dynamic updating for my setting, but I am afraid it's terribly outdated now. If your goal is language modeling (even of code), please consider getting a more recent language modeling example from Tensorflow (e.g. [Tensorflow Eager](https://www.tensorflow.org/guide/eager) is much more usable); they release [updated model examples](https://github.com/tensorflow/models/) for e.g. text modeling with every revision. Making it dynamic at test time should be a very small change now (this used to be much harder). I am happy to advise on this as well or even meet up in person if you are at UCDavis :)
-- Vincent

**Comment by hsezhiyan** [comment]
Hello Vincent,

Thanks for your response! I'll be sure to check out the TensorFlow model.

And I'd very much like to meet in person! I'm currently in Davis. I sent you a request on LinkedIn. Hopefully we can chat there.
