### ISSUE TITLE
Strange error.

### ISSUE THREAD

**Issue by mpatsis** [SLP-team/SLP-Core#14]
Any idea why I get this error when trying to learn a simple 3-gram model? I've tried running the jar with both Java 10 and 12. 

java -jar slp-core.jar train --train /mnt/datastore/inf/groups/cdt_ds/mpatsis/PhD/rafaelository/data/Miltos/tokenized/training/tr --counter /home/mpatsis/Documents/models/n-grams/3-gram-th5  -v /home/mpatsis/Documents/models/n-grams/3-gram-th5.vocab -o 3 -u 5 -l blank -m jm
Using lexer WhitespaceLexer
Retrieving vocabulary from file
Counting: 1M tokens processed in 3s
Counting: 2M tokens processed in 7s
Counting: 3M tokens processed in 11s
Counting: 4M tokens processed in 14s
Counting: 5M tokens processed in 19s
Counting: 6M tokens processed in 22s
Counting: 7M tokens processed in 26s
Counting: 8M tokens processed in 30s
Counting: 9M tokens processed in 34s
Counting: 10M tokens processed in 37s
Counting: 11M tokens processed in 42s
Counting: 12M tokens processed in 46s
Counting: 13M tokens processed in 49s
Counting: 14M tokens processed in 53s
Counting: 15M tokens processed in 57s
Counting complete: 15737855 tokens processed in 60s
Writing counter to file
WARNING: Illegal reflective access by org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction$1 (file:/home/mpatsis/src/SLP-Core/slp-core.jar) to constructor java.io.OptionalDataException(boolean)
Writing counter to: /home/mpatsis/Documents/models/n-grams/3-gram-th5
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jboss.marshalling.river.RiverMarshaller.<clinit>(RiverMarshaller.java:1233)
	at org.jboss.marshalling.river.RiverMarshallerFactory.createMarshaller(RiverMarshallerFactory.java:54)
	at slp.core.counting.io.CounterIO.writeCounter(CounterIO.java:43)
	at slp.core.CLI.train(CLI.java:369)
	at slp.core.CLI.main(CLI.java:114)
Caused by: java.lang.IllegalStateException: No standard field found for reverse order comparator!
	at org.jboss.marshalling.river.Protocol.<clinit>(Protocol.java:220)
	... 5 more

**Comment by VHellendoorn** [comment]
Hi, that's probably the Java version. At some point (I think JDK 9), calling deprecated methods became a runtime warning, and the idea was to make it a runtime error later on, as part of a push to make depredations actually matter. I suspect around jdk10-12, you'd get this behavior; sorry about that. It's not actually my code, but JBoss using the outdated Java reflect api; perhaps upgrading that dependency would solve it (they didn't fix it last I checked but that's a while ago -- probably getting time to retire this code base)

**Comment by mpatsis** [comment]
Thanks Vincent! Building the current source as a Java 10 project worked for me.
I'll try to checkout the older version and make a jar from that.

**Comment by SarahBoening** [comment]
I got the same error with Java 13 and running it on Java 10 did not fix it for me. However, I upgraded JBoss to 2.0.9.Final and this seems to have fixed the problem.
