### ISSUE TITLE
Predicted tokens?

### ISSUE THREAD

**Issue by antonio-mastropaolo** [SLP-team/SLP-Core#17]
Hello everyone,

I was wondering which is the fastest way to retrieve the predicted token when predicting.
Basically, I want to analyze what's going on when the predicted token is wrong from a qualitative standpoint.

I really appreciate any help you can provide.

**Comment by VHellendoorn** [comment]
Hi,

It might help to clarify what you mean by "fastest". Both the command-line and the code API have a `predict` mode that emits a probability distribution over next token candidates and can write those to file. See the Wiki examples or the `example` folder for some demonstrations. The latter mostly has entropy-based examples, but the switch to getting predictions is very minor (just switch a call like `modelFile` to `predictFile`, see the ModelRunner API).

Both of those generate one word at the time, but neither will provide much insight into the exact reason for their prediction -- that comes down to the mix of (many) language models' counts and weights. If you want rich insights there, it's probably best to fork the project and inject custom code logging those intermediate computations.

-Vincent

**Comment by antonio-mastropaolo** [comment]
Thanks a lot, @VHellendoorn .
I was using the jar with the command line, but as you suggested, the only way to get more information is to put some logging messages here and there while using the ModelRunner API, that BTW is what I'm doing right now.
The last thing I'd like to task is the following: let's assume I've already trained a model ( I have the .counts file), and I want to use it to generate some predictions alongside the cache mechanism.
Are the following lines enough to plug in the cache mechanism when testing?

```
Model model = new JMModel(3, counter);
model = MixModel.standard(model, new CacheModel()); //adding cache for testing
ModelRunner modelRunner = new ModelRunner(model, lexerRunner, vocabulary); 
Stream<Pair<File, List<List<Double>>>> modeledFiles = modelRunner.modelDirectory(new File(test_dir));
```

--_Antonio_

**Comment by VHellendoorn** [comment]
Hi! Yes, I'd say that looks correct.

Though TBH, it's been quite a while since I last used this toolkit :) A quick sanity check would be to look at the entropy/prediction quality with vs. without the cache; if there's at all a locality effect, this current version should be a lot better than the one without cache.

-Vincent
